export const TEACHER_DATA = {
    "mentor":[
        {
            "code":"0",
            "name":"未知"
        },
        {
            "code":"其他",
            "name":"其他"
        },
        {
            "code":"博士生导师",
            "name":"博士生导师"
        },
        {
            "code":"硕士生导师",
            "name":"硕士生导师"
        }
    ],
    "education":[
        {
            "code":"0",
            "name":"未知"
        },
        {
            "code":"中等专科毕业",
            "name":"中等专科毕业"
        },
        {
            "code":"中等职业教育",
            "name":"中等职业教育"
        },
        {
            "code":"初中毕业",
            "name":"初中毕业"
        },
        {
            "code":"博士研究生毕业",
            "name":"博士研究生毕业"
        },
        {
            "code":"大学专科教育",
            "name":"大学专科教育"
        },
        {
            "code":"大学专科毕业",
            "name":"大学专科毕业"
        },
        {
            "code":"大学本科教育",
            "name":"大学本科教育"
        },
        {
            "code":"大学本科毕业",
            "name":"大学本科毕业"
        },
        {
            "code":"普通高中毕业",
            "name":"普通高中毕业"
        },
        {
            "code":"研究生教育",
            "name":"研究生教育"
        },
        {
            "code":"研究生班毕业",
            "name":"研究生班毕业"
        },
        {
            "code":"研究生班结业",
            "name":"研究生班结业"
        },
        {
            "code":"硕士研究生毕业",
            "name":"硕士研究生毕业"
        },
        {
            "code":"硕士研究生肄业",
            "name":"硕士研究生肄业"
        }
    ],
    "nation":[
        {
            "code":"东乡族",
            "name":"东乡族"
        },
        {
            "code":"仫佬族",
            "name":"仫佬族"
        },
        {
            "code":"侗族",
            "name":"侗族"
        },
        {
            "code":"其他",
            "name":"其他"
        },
        {
            "code":"回族",
            "name":"回族"
        },
        {
            "code":"土家族",
            "name":"土家族"
        },
        {
            "code":"壮族",
            "name":"壮族"
        },
        {
            "code":"朝鲜族",
            "name":"朝鲜族"
        },
        {
            "code":"毛难族",
            "name":"毛难族"
        },
        {
            "code":"水族",
            "name":"水族"
        },
        {
            "code":"汉族",
            "name":"汉族"
        },
        {
            "code":"满族",
            "name":"满族"
        },
        {
            "code":"瑶族",
            "name":"瑶族"
        },
        {
            "code":"苗族",
            "name":"苗族"
        },
        {
            "code":"蒙古族",
            "name":"蒙古族"
        },
        {
            "code":"达斡尔族",
            "name":"达斡尔族"
        },
        {
            "code":"锡伯族",
            "name":"锡伯族"
        }
    ],
    "sex":[
        {
            "code":"女",
            "name":"女"
        },
        {
            "code":"男",
            "name":"男"
        }
    ],
    "dept":[
        {
            "code":"0",
            "name":"未知"
        },
        {
            "code":"1001",
            "name":"校领导"
        },
        {
            "code":"101",
            "name":"党委办公室、党委统战部（校长办公室、督查督办工作办公室）"
        },
        {
            "code":"102",
            "name":"党委组织部（机关党委）"
        },
        {
            "code":"103",
            "name":"党委宣传部（党委教师工作部）"
        },
        {
            "code":"104",
            "name":"党委学生工作部（处）"
        },
        {
            "code":"105",
            "name":"党委武装部（处）"
        },
        {
            "code":"106",
            "name":"党委巡察办公室、纪委办公室（监察室）"
        },
        {
            "code":"107",
            "name":"人事处 （职改办）"
        },
        {
            "code":"108",
            "name":"教务处（质量监测与管理办公室、教师教学发展中心）"
        },
        {
            "code":"109",
            "name":"科技处（学科建设办公室）"
        },
        {
            "code":"110",
            "name":"发展规划处、研究生处"
        },
        {
            "code":"111",
            "name":"招生就业处"
        },
        {
            "code":"112",
            "name":"后勤基建处"
        },
        {
            "code":"113",
            "name":"财务处"
        },
        {
            "code":"114",
            "name":"国有资产管理处"
        },
        {
            "code":"115",
            "name":"国际交流处（港澳台事务办公室）"
        },
        {
            "code":"116",
            "name":"审计处"
        },
        {
            "code":"117",
            "name":"离退休工作处"
        },
        {
            "code":"201",
            "name":"海洋学院"
        },
        {
            "code":"202",
            "name":"海运学院（船员培训中心）"
        },
        {
            "code":"203",
            "name":"机械与船舶海洋工程学院（工程训练中心）"
        },
        {
            "code":"204",
            "name":"石油与化工学院"
        },
        {
            "code":"205",
            "name":"食品工程学院"
        },
        {
            "code":"206",
            "name":"电子与信息工程学院"
        },
        {
            "code":"207",
            "name":"资源与环境学院"
        },
        {
            "code":"208",
            "name":"人文学院"
        },
        {
            "code":"209",
            "name":"经济管理学院"
        },
        {
            "code":"210",
            "name":"教育学院"
        },
        {
            "code":"211",
            "name":"陶瓷与设计学院"
        },
        {
            "code":"212",
            "name":"理学院"
        },
        {
            "code":"213",
            "name":"建筑工程学院"
        },
        {
            "code":"214",
            "name":"马克思主义学院"
        },
        {
            "code":"215",
            "name":"体育教学部"
        },
        {
            "code":"216",
            "name":"继续教育学院"
        },
        {
            "code":"218",
            "name":"创新创业学院"
        },
        {
            "code":"301",
            "name":"图书馆"
        },
        {
            "code":"302",
            "name":"学报编辑部"
        },
        {
            "code":"303",
            "name":"网络与教育技术中心"
        },
        {
            "code":"304",
            "name":"档案馆（校史馆）"
        },
        {
            "code":"401",
            "name":"北部湾大学工会委员会"
        },
        {
            "code":"402",
            "name":"共青团北部湾大学委员会"
        },
        {
            "code":"501",
            "name":"北部湾海洋文化研究中心"
        },
        {
            "code":"503",
            "name":"钦州发展研究院"
        },
        {
            "code":"504",
            "name":"先端科学技术研究院"
        },
        {
            "code":"505",
            "name":"广西高校转型发展研究院"
        },
        {
            "code":"901",
            "name":"湾大后勤服务集团"
        }
    ],
    "employment":[
        {
            "code":"0",
            "name":"未知"
        },
        {
            "code":"在编",
            "name":"在编"
        },
        {
            "code":"非在编",
            "name":"非在编"
        }
    ],
    "type":[
        {
            "code":"0",
            "name":"未知"
        },
        {
            "code":"专任教师",
            "name":"专任教师"
        },
        {
            "code":"其他专业技术人员",
            "name":"其他专业技术人员"
        },
        {
            "code":"工勤人员",
            "name":"工勤人员"
        },
        {
            "code":"教辅人员",
            "name":"教辅人员"
        },
        {
            "code":"校本部教职工",
            "name":"校本部教职工"
        },
        {
            "code":"科研机构人员",
            "name":"科研机构人员"
        },
        {
            "code":"聘请校外教师",
            "name":"聘请校外教师"
        },
        {
            "code":"行政人员",
            "name":"行政人员"
        }
    ],
    "age":[
        {
            "code":"0",
            "name":"未知"
        },
        {
            "code":"23",
            "name":"23岁"
        },
        {
            "code":"24",
            "name":"24岁"
        },
        {
            "code":"25",
            "name":"25岁"
        },
        {
            "code":"26",
            "name":"26岁"
        },
        {
            "code":"27",
            "name":"27岁"
        },
        {
            "code":"28",
            "name":"28岁"
        },
        {
            "code":"29",
            "name":"29岁"
        },
        {
            "code":"30",
            "name":"30岁"
        },
        {
            "code":"31",
            "name":"31岁"
        },
        {
            "code":"32",
            "name":"32岁"
        },
        {
            "code":"33",
            "name":"33岁"
        },
        {
            "code":"34",
            "name":"34岁"
        },
        {
            "code":"35",
            "name":"35岁"
        },
        {
            "code":"36",
            "name":"36岁"
        },
        {
            "code":"37",
            "name":"37岁"
        },
        {
            "code":"38",
            "name":"38岁"
        },
        {
            "code":"39",
            "name":"39岁"
        },
        {
            "code":"40",
            "name":"40岁"
        },
        {
            "code":"41",
            "name":"41岁"
        },
        {
            "code":"42",
            "name":"42岁"
        },
        {
            "code":"43",
            "name":"43岁"
        },
        {
            "code":"44",
            "name":"44岁"
        },
        {
            "code":"45",
            "name":"45岁"
        },
        {
            "code":"46",
            "name":"46岁"
        },
        {
            "code":"47",
            "name":"47岁"
        },
        {
            "code":"48",
            "name":"48岁"
        },
        {
            "code":"49",
            "name":"49岁"
        },
        {
            "code":"50",
            "name":"50岁"
        },
        {
            "code":"51",
            "name":"51岁"
        },
        {
            "code":"52",
            "name":"52岁"
        },
        {
            "code":"53",
            "name":"53岁"
        },
        {
            "code":"54",
            "name":"54岁"
        },
        {
            "code":"55",
            "name":"55岁"
        },
        {
            "code":"56",
            "name":"56岁"
        },
        {
            "code":"57",
            "name":"57岁"
        },
        {
            "code":"58",
            "name":"58岁"
        },
        {
            "code":"59",
            "name":"59岁"
        },
        {
            "code":"60",
            "name":"60岁"
        },
        {
            "code":"61",
            "name":"61岁"
        },
        {
            "code":"62",
            "name":"62岁"
        },
        {
            "code":"63",
            "name":"63岁"
        },
        {
            "code":"65",
            "name":"65岁"
        },
        {
            "code":"66",
            "name":"66岁"
        },
        {
            "code":"67",
            "name":"67岁"
        },
        {
            "code":"68",
            "name":"68岁"
        },
        {
            "code":"69",
            "name":"69岁"
        },
        {
            "code":"73",
            "name":"73岁"
        }
    ]
}

export const STUDENT_DATA = {
    "college":[
        {
            "create_by":"1705406110",
            "code":"null",
            "name":"机械与船舶海洋工程学院",
            "create_name":"廖进章"
        },
        {
            "create_by":"1549407232",
            "code":"201",
            "sys_org_code":"201",
            "name":"海洋学院",
            "create_name":"农杰元"
        },
        {
            "create_by":"1512401125",
            "code":"202",
            "sys_org_code":"202",
            "name":"海运学院",
            "create_name":"易恒智"
        },
        {
            "create_by":"1505406231",
            "code":"203",
            "sys_org_code":"203",
            "name":"机械与船舶海洋工程学院",
            "create_name":"陈广钦"
        },
        {
            "create_by":"1511401105",
            "code":"204",
            "sys_org_code":"204",
            "name":"石油与化工学院",
            "create_name":"李凤秀"
        },
        {
            "create_by":"1514405134",
            "code":"205",
            "sys_org_code":"205",
            "name":"食品工程学院",
            "create_name":"张国泰"
        },
        {
            "create_by":"1504405432",
            "code":"206",
            "sys_org_code":"206",
            "name":"电子与信息工程学院",
            "create_name":"陈俊炎"
        },
        {
            "create_by":"1607401101",
            "code":"207",
            "sys_org_code":"207",
            "name":"资源与环境学院",
            "create_name":"奚有谦"
        },
        {
            "create_by":"1502401314",
            "code":"208",
            "sys_org_code":"208",
            "name":"人文学院",
            "create_name":"张圆梦"
        },
        {
            "create_by":"1501402128",
            "code":"209",
            "sys_org_code":"209",
            "name":"经济管理学院",
            "create_name":"李宗晓"
        },
        {
            "create_by":"1609407101",
            "code":"210",
            "sys_org_code":"210",
            "name":"教育学院",
            "create_name":"莫文敬"
        },
        {
            "create_by":"1506411331",
            "code":"211",
            "sys_org_code":"211",
            "name":"陶瓷与设计学院",
            "create_name":"张思敏"
        },
        {
            "create_by":"1613401101",
            "code":"212",
            "sys_org_code":"212",
            "name":"理学院",
            "create_name":"陶建金"
        },
        {
            "create_by":"1611414238",
            "code":"213",
            "sys_org_code":"213",
            "name":"建筑工程学院",
            "create_name":"李玉海"
        },
        {
            "create_by":"1502311108",
            "code":"81",
            "sys_org_code":"81",
            "name":"国际教育与外国语学院",
            "create_name":"刘伟"
        }
    ],
    "nation":[
        {
            "code":"京族",
            "name":"京族"
        },
        {
            "code":"仡佬族",
            "name":"仡佬族"
        },
        {
            "code":"仫佬族",
            "name":"仫佬族"
        },
        {
            "code":"佤族",
            "name":"佤族"
        },
        {
            "code":"侗族",
            "name":"侗族"
        },
        {
            "code":"傣族",
            "name":"傣族"
        },
        {
            "code":"其他",
            "name":"其他"
        },
        {
            "code":"哈尼族 ",
            "name":"哈尼族 "
        },
        {
            "code":"回族",
            "name":"回族"
        },
        {
            "code":"土家族 ",
            "name":"土家族 "
        },
        {
            "code":"土族",
            "name":"土族"
        },
        {
            "code":"壮族",
            "name":"壮族"
        },
        {
            "code":"布依族",
            "name":"布依族"
        },
        {
            "code":"布朗族",
            "name":"布朗族"
        },
        {
            "code":"彝族",
            "name":"彝族"
        },
        {
            "code":"朝鲜族",
            "name":"朝鲜族"
        },
        {
            "code":"毛南族",
            "name":"毛南族"
        },
        {
            "code":"毛难族",
            "name":"毛难族"
        },
        {
            "code":"水族",
            "name":"水族"
        },
        {
            "code":"汉族",
            "name":"汉族"
        },
        {
            "code":"满族",
            "name":"满族"
        },
        {
            "code":"瑶族",
            "name":"瑶族"
        },
        {
            "code":"畲族",
            "name":"畲族"
        },
        {
            "code":"白族",
            "name":"白族"
        },
        {
            "code":"穿青人 ",
            "name":"穿青人 "
        },
        {
            "code":"纳西族",
            "name":"纳西族"
        },
        {
            "code":"羌族",
            "name":"羌族"
        },
        {
            "code":"苗族",
            "name":"苗族"
        },
        {
            "code":"蒙古族 ",
            "name":"蒙古族 "
        },
        {
            "code":"藏族",
            "name":"藏族"
        },
        {
            "code":"锡伯族 ",
            "name":"锡伯族 "
        },
        {
            "code":"黎族",
            "name":"黎族"
        }
    ],
    "grade":[
        {
            "create_by":"1605417306",
            "code":"2019",
            "sys_org_code":"204",
            "name":"2019",
            "create_name":"韦球"
        },
        {
            "create_by":"1502311108",
            "code":"2018",
            "sys_org_code":"81",
            "name":"2018",
            "create_name":"刘伟"
        },
        {
            "create_by":"1501402128",
            "code":"2017",
            "sys_org_code":"209",
            "name":"2017",
            "create_name":"李宗晓"
        },
        {
            "create_by":"1501415223",
            "code":"2016",
            "sys_org_code":"209",
            "name":"2016",
            "create_name":"马俊仁"
        }
    ],
    "sex":[
        {
            "create_by":"1501419308",
            "code":"女",
            "sys_org_code":"209",
            "name":"女",
            "create_name":"刘权"
        },
        {
            "create_by":"1501402128",
            "code":"男",
            "sys_org_code":"209",
            "name":"男",
            "create_name":"李宗晓"
        }
    ],
    "comeFrom":[
        {
            "code":"广西壮族自治区",
            "name":"广西壮族自治区",
            "count":13589
        },
        {
            "code":"湖南省",
            "name":"湖南省",
            "count":456
        },
        {
            "code":"null",
            "name":"未知",
            "count":426
        },
        {
            "code":"四川省",
            "name":"四川省",
            "count":397
        },
        {
            "code":"江西省",
            "name":"江西省",
            "count":331
        },
        {
            "code":"河北省",
            "name":"河北省",
            "count":264
        },
        {
            "code":"广东省",
            "name":"广东省",
            "count":262
        },
        {
            "code":"山东省",
            "name":"山东省",
            "count":236
        },
        {
            "code":"河南省",
            "name":"河南省",
            "count":214
        },
        {
            "code":"贵州省",
            "name":"贵州省",
            "count":205
        },
        {
            "code":"云南省",
            "name":"云南省",
            "count":197
        },
        {
            "code":"安徽省",
            "name":"安徽省",
            "count":136
        },
        {
            "code":"重庆市",
            "name":"重庆市",
            "count":135
        },
        {
            "code":"海南省",
            "name":"海南省",
            "count":128
        },
        {
            "code":"福建省",
            "name":"福建省",
            "count":118
        },
        {
            "code":"江苏省",
            "name":"江苏省",
            "count":112
        },
        {
            "code":"辽宁省",
            "name":"辽宁省",
            "count":82
        },
        {
            "code":"湖北省",
            "name":"湖北省",
            "count":74
        },
        {
            "code":"甘肃省",
            "name":"甘肃省",
            "count":65
        },
        {
            "code":"山西省",
            "name":"山西省",
            "count":61
        },
        {
            "code":"浙江省",
            "name":"浙江省",
            "count":61
        },
        {
            "code":"黑龙江省",
            "name":"黑龙江省",
            "count":61
        },
        {
            "code":"吉林省",
            "name":"吉林省",
            "count":53
        },
        {
            "code":"青海省",
            "name":"青海省",
            "count":52
        },
        {
            "code":"陕西省",
            "name":"陕西省",
            "count":43
        },
        {
            "code":"宁夏回族自治区",
            "name":"宁夏回族自治区",
            "count":37
        },
        {
            "code":"内蒙古自治区",
            "name":"内蒙古自治区",
            "count":22
        },
        {
            "code":"天津市",
            "name":"天津市",
            "count":6
        },
        {
            "code":"新疆维吾尔自治区",
            "name":"新疆维吾尔自治区",
            "count":3
        }
    ],
    "age":[
        {
            "code":"",
            "name":"未知"
        },
        {
            "code":"1",
            "name":"1岁"
        },
        {
            "code":"15",
            "name":"15岁"
        },
        {
            "code":"16",
            "name":"16岁"
        },
        {
            "code":"17",
            "name":"17岁"
        },
        {
            "code":"18",
            "name":"18岁"
        },
        {
            "code":"19",
            "name":"19岁"
        },
        {
            "code":"20",
            "name":"20岁"
        },
        {
            "code":"21",
            "name":"21岁"
        },
        {
            "code":"22",
            "name":"22岁"
        },
        {
            "code":"23",
            "name":"23岁"
        },
        {
            "code":"24",
            "name":"24岁"
        },
        {
            "code":"25",
            "name":"25岁"
        },
        {
            "code":"26",
            "name":"26岁"
        },
        {
            "code":"27",
            "name":"27岁"
        },
        {
            "code":"28",
            "name":"28岁"
        },
        {
            "code":"29",
            "name":"29岁"
        },
        {
            "code":"30",
            "name":"30岁"
        }
    ]
}